phac-nml/galaxy_tools

packages/package_srst2_0_1_4_6/.shed.yml, packages/package_srst2_0_1_4_6/tool_dependencies.xml
Also fixed the tool_dependencies for 0.1.4.5
=> Added srst2 0.1.6 package

packages/package_mrbayes_3_2_6/tool_dependencies.xml
Removed sudo, added prefix to configure
=> un-sudo'ing mrbayes

packages/package_spolpred_1_0_0/.shed.yml, packages/package_spolpred_1_0_0/tool_dependencies.xml, tools/spolpred/.shed.yml, tools/spolpred/spolpred.sh, tools/spolpred/spolpred.xml, tools/spolpred/tool_dependencies.xml
As far as I know the wrapper works properly, so I figured I'll do a pull request for whenever the cpp gets fixed
=> Spolpred wrapper

packages/package_mrbayes_3_2_6/tool_dependencies.xml, tools/mrbayes/mrbayes.xml
Also added exit code catching for >=1
=> Fixed issues with paths, setting seed/swapseed

tools/collapse_collection/merge.xml
Had to use awk to put it on every line.
=> Now can add dataset name to every line in the file.

tools/fasta_extract/.shed.yml, tools/fasta_extract/fa-extract-few.pl, tools/fasta_extract/fa-extract-sequence.xml, tools/fasta_extract/tool_dependencies.xml
Tested (installed and ran) on bgruening's galaxy docker
=> Adding fasta_extract and updated to include bio_perl requirement

packages/package_mrbayes_3_2_6/tool_dependencies.xml, packages/package_python_3_4_bioext_0_17_3/tool_dependencies.xml, packages/package_python_3_4_biopython_1_66/tool_dependencies.xml, packages/package_python_3_4_cython_0_23_4/tool_dependencies.xml, packages/package_python_3_4_fakemp_0_9_1/tool_dependencies.xml, packages/package_python_3_4_hivclustering_1_2_3/tool_dependencies.xml, packages/package_python_3_4_hivtrace_0_1_4/tool_dependencies.xml, packages/package_python_3_4_hppy_0_9_6/tool_dependencies.xml, packages/package_python_3_4_numpy_1_10_1/tool_dependencies.xml, packages/package_python_3_4_pysam_0_8_3/tool_dependencies.xml, packages/package_python_3_4_scipy_0_16/tool_dependencies.xml, packages/package_python_3_4_six_1_10_0/tool_dependencies.xml, packages/package_spades_3_6_1/tool_dependencies.xml, packages/package_spades_3_6_2/tool_dependencies.xml, packages/package_spades_3_8_0/tool_dependencies.xml, packages/package_spades_3_9_0/tool_dependencies.xml, packages/package_tn93_1_0_2/tool_dependencies.xml, tools/bundle_collections/bundle_collection.xml, tools/hivtrace/hivtrace.xml, tools/mrbayes/mrbayes.xml, tools/spolpred/spolpred.xml
All tool wrapper pass planemo shed_lint. Mostly all other changes were caused by changing tool wrapper standards
=> added sha256sum to all packages that needed it. 

packages/package_srst2_0_1_4_6/tool_dependencies.xml, tools/srst2/srst2.xml
Had to modify bash code to add the minins variable if the maxins is set (a value of 0 makes the previous if statement false)
@Takadonet @ericenns
=> Srst2 minins variable

packages/package_pandoc_0_0_1/.shed.yml, packages/package_pandoc_0_0_1/tool_dependencies.xml, tools/plasmid_profiler/.shed.yml, tools/plasmid_profiler/plasmid_profiler.xml, tools/plasmid_profiler/tool_dependencies.xml, tools/plasmid_profiler_suite/.shed.yml, tools/plasmid_profiler_suite/repository_dependencies.xml
Initial version of the Plasmid Profiler tool and suite.
@Takadonet @ericenns
=> Plasmid Profiler, suite and required package

tools/plasmidspades/plasmidSPAdes.xml, tools/plasmidspades/tool_dependencies.xml
Now using version 3.9.0 of spades.
=> Changing Plasmid Spades wrapper

packages/package_srst2_0_1_4_6/tool_dependencies.xml, tools/plasmid_profiler/plasmid_profiler.xml, tools/plasmid_profiler/tool_dependencies.xml, tools/plasmid_profiler_suite/repository_dependencies.xml
=> Package SRST2 fixing LD_LIBRARY_PATH

tools/combine_tabular_collection/.shed.yml, tools/combine_tabular_collection/combine.sh, tools/combine_tabular_collection/combine.xml
=> adding combine tabular collection to phac-nml

tools/mrbayes/mrbayes.xml
Update help tags as param tags attribute
Clean labels
=> Update of syntax and indentation

tools/stringmlst/split_by_allele.py, tools/stringmlst/stringmlst.xml, tools/stringmlst/test-data/results.tsv, tools/stringmlst/tool_dependencies.xml
=> Stringmlst bioconda

tools/hansel/bio_hansel.xml
1) hansel now will have file names in results.tab and match_results.tab
2) removed some older readme text.
=> Updating hansel output to include file names.

tools/assemblystats/.shed.yml, tools/assemblystats/README_ASSEMBLY_STATS, tools/assemblystats/assembly_stats_txt.py, tools/assemblystats/assembly_stats_txt.xml, tools/assemblystats/fasta_summary.pl, tools/assemblystats/test-data/Assembly_statistics_-_SRR1002850_SMALL.fasta.tabular
This is a Galaxy wrapper for assemblystats, part of the migration of the internal toolshed to Github.
=> Galaxy Wrapper for Assemblystats

tools/seqtk_nml/seqtk_nml.xml
Changing the collections portion of the script, and the help section.
=> Fixing the collections parameters, help section for Seqtk_NML

tools/hansel/bio_hansel.xml
This is the new version of `Bio_Hansel` which adds the following improvements.
+ Quality Checking
+ Technician's Output
+ Enteritidis Scheme 0.7.0
+ Min K-mer Freq = 8, Max K-mer Freq = 1000
+ Fix for Inconsistent Subtype Function
=> Updating bio_hansel Galaxy wrapper to 1.0.0.

tools/hansel/bio_hansel.xml
Includes fixes for:
- Fatal Error 1
- QC Error 4 not working as expected.
=> Updating bio_hansel to 1.1.3

tools/hansel/bio_hansel.xml
Adding new parameter that lets the user specify the minimum coverage before the tool displays a low coverage warning.
=> Updating Bio_Hansel Wrapper

tools/combineJSON/.shed.yml, tools/combineJSON/combineJSON.xml
No uppercase letters allowed in .shed.yml file. Changing name to combine_json.
=> Changing to combineJson to combine_json

tools/staramr/staramr_search.xml
Updates to `staramr` version 0.2.1
=> Updated staramr to 0.2.1

tools/biohansel/biohansel.xml
Added compatibility to extract names from `.fastqsanger.gz` files.
=> Add .sanger.gz to REGEX

tools/staramr/staramr_search.xml
Updates `staramr` to version `0.4.0`, which includes support for scanning for point mutations from *campylobacter*.
=> Updated staramr to version 0.4.0

tools/biohansel/biohansel.xml
I've also changed the publication title and list of authors
=> Updated biohansel v.2.4.0 wrapper

tools/staramr/staramr_search.xml
Fixing [bug ](https://github.com/phac-nml/staramr/issues/118)
=> fix bug where could not re-run staramr

tools/pangolin/macros.xml, tools/pangolin/pangolin.xml
- Added trees command
- Updated version to match bioconda version
=> Pangolin v1.1.5

tools/pangolin/macros.xml, tools/pangolin/pangolin.xml, tools/pangolin/test-data/lineage_report.tsv
- Small changes to test data to reflect new lineages
- Small changes to tests as the results are not always the exact same (value=99 sometimes and 100 other times)
=> Update Pangolin to v1.1.11

tools/pangolin/macros.xml, tools/pangolin/pangolin.xml
Next round of updates, only really the version bump.
I did add the authors new site as a link along with a small wording change too
=> Update pangolin to v1.1.13

tools/pangolin/macros.xml, tools/pangolin/pangolin.xml
- Bump to version
- Added new param (-p --> Putative lineages)
=> Update Pangolin to v1.1.4

tools/cryptogenotyper/cryptogenotyper.xml
Hello!
This is an updated recipe with more robust code as per best practices code [https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html](https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html)
Mainly it is similar to previous version, but single quotes are removed and description is shorter than previous one
Addressing  requests from [PR #204](https://github.com/phac-nml/galaxy_tools/pull/204)
=> Cryptogenotyper v1.0 + galaxy0 release accommodating requested changes from PR#204

tools/gnali/gnali.xml, tools/gnali/macros.xml
=> gNALI 1.0.3

tools/mob_suite/macros.xml
=> MOB-Suite v3.0.3 bump

.github/workflows/pr.yaml, tools/staramr/staramr_search.xml, tools/staramr/test-data/genes_to_exclude.tsv, tools/staramr/test-data/test1-pointfinder-ecoli.tsv, tools/staramr/test-data/test1-pointfinder.tsv
- Updated staramr conda version to v0.9.1
- Updated mlst to v2.23.0
- There were no changes in schemes when compared to v2.22.0
- Added to and alphabetized the list of validated organisms.
- Updated Galaxy tests and fixed test problems.
=> Updating staramr to 0.9.1

tools/spatyper/spatyper.xml
Quick Patch to correct versioning
=> Hotfix Profile Ver. Update

tools/mykrobe_parser/mykrobe_parser.xml
The user of mykrobe parser was requesting that the label be changed from "report" to "Mykrobe report"
Small adjustment, not sure if anything else needs to be done other than the label change
=> Update mykrobe_parser for user request
