phac-nml/galaxy_tools

tools/spolpred/spolpred.sh
Thanks to @ericenns for the regex wizardry. I tested this with and without spaces and it works as intended now
Sample output:
(don't mind the 0s, I ran the first one with reverse)
=> Fixed regex for sed to allow white spaces in names

tools/mrbayes/mrbayes.xml
It was actually returning 0, even when error was encountered. So I set the quitonerror flag to 'yes' instead of 'no'. Seems to have fixed the issue
=> Made mrbayes return 1 on error instead of 0

packages/package_srst2_0_1_4_6/tool_dependencies.xml, tools/srst2/tool_dependencies.xml
Added Python 2.7.10, Numpy 1.9 and Scipy 0.14. 
Tested this install on a Docker container of bgruening Galaxy Docker. Installs and runs.
=> Adding Python Dependencies to SRST2

packages/package_srst2_0_1_4_6/tool_dependencies.xml
Numpy requires atlas to run. Was missed in initial testing as environments tested had Numpy already installed. @Takadonet @ericenns
=> Adding Atlas Requirement

tools/sistr_cmd/sistr_cmd.xml
Minor change in tool wrapper command to ensure that sistr_cmd output is generated with older versions of Galaxy and also simplify/refactor the command code.
=> Fix sistr results output not being generated in older versions of Galaxy

tools/hansel/bio_hansel.xml
Modified the wrapper so that for paired collection's we use the name of the collection rather than the individual file names of the entries in that collection.
=> Fixing paired collection same name error.

tools/combineJSON/combineJSON.py
combine_json should be allowed to take in one input, and simply pass through the same result as the output. This is required within the bio_hansel workflow, for the single file case.
=> Updating combine_json's Input Capabilities

tools/hansel/bio_hansel.xml
- Updated bio_hansel to 1.3.1, which uses the updated Enteritidis scheme
- Fixed citation duplication
=> Updating bio_hansel to 1.3.1

tools/staramr/staramr_search.xml, tools/staramr/test-data/16S rc_gyrA rc_beta-lactam spaces (extra:characters).fsa, tools/staramr/test-data/test4-summary.tsv
This fixes an issue where there were spaces (or other characters) in the Galaxy tool dataset name, see https://github.com/phac-nml/staramr/issues/18.  In this case, the dataset name was **Shovill on data 11 and data 10: Contigs.fasta**, but this caused issues when running staramar (in `makeblastdb`).
My solution for Galaxy is to swap out spaces and () characters with an underscore _.
I did not increment the Galaxy tool version number since this is just a small bugfix (when submitting to the Galaxy toolshed, this version will now labelled version `0.2.0`, though the older version of the tool will still be kept around if needed).
=> Fixed spaces in name

tools/mykrobe_parser/mykrobe_parser.xml
now getting the element_identifier and not the filename itself. Was causing issues where same file name was being overwritten all the time. Switch to soft link instead of cp.
=> Fix bug when running collection

tools/biohansel/biohansel.xml
This is a fix for fastq dump files, that have a colon in the name.
In the output names like `SRR190010:forward` will be fixed to show only `SRR190010`.
=> Add fastq_dump colon regex

tools/ectyper/ectyper.xml
Very minor change to the previous wrapper. Now incorporating ability to run mash distance calculations on the genomes that could not be typed using the O and H alleles.
=> MASH distance feature implementation for ectyper v0.8.1

tools/mykrobe_parser/mykrobe_parser.R, tools/mykrobe_parser/mykrobe_parser.xml
- Fixed eis not being placed into Mykrobe_Kanamycin_eis
- Split Moxifloxacin and Ofloxacin into separate drug and mutation columns
- Renamed LIMS_Filename to Mutation_set_version for LIMS compatibility
- tested in R
=> Compatibility with Mykrobe Predictor 0.6.1

tools/staramr/.shed.yml, tools/staramr/staramr_search.xml
When uploading files by URL into a collection, element identifiers will be the full URL, and cause a problem in the symlinking step, this adds forward slash to the set of sanitized characters
ping @apetkau
=> Staramr: strip slashes from input file names

tools/biohansel/biohansel.xml
Fix for #148  using the same method as the refseq masher fix in PR #138. Add .fasta to all files and then remove it from the output results so that it isn't in any of the sample names.
Does this by splitting the extension from the rest of the name and changing the extension to .fasta.
ex. CP10191.1.1.fna --> CP10191.1.1.fasta
If no file extension present, it just adds the .fasta to it
=> Wrapper accepts fasta files without .fasta extension

tools/mob_suite/mob_recon.xml, tools/mob_suite/mob_typer.xml
I'd like to use a more recent version of mob_suite in an [IRIDA pipeline](https://github.com/dfornika/irida-plugin-plasmid-screen) that I'm developing.
Rather than go straight from `1.4.8` to `2.0.2` I thought it might make sense to update incrementally, so I'll submit a few PRs so that each version can be made available on the Galaxy toolshed.
=> Update mob_suite to v1.4.9.1

tools/mob_suite/macros.xml, tools/mob_suite/mob_recon.xml, tools/mob_suite/mob_typer.xml
This wrapper is for MOB-Suite v3.0.1 addressing `pandas` and `ete3` libraries issues. This wrapper would make MOB-Suite v3.0.1 available on Galaxy. Previous Galaxy versions might encounter installation issues due to no restriction on pandas upper version limits. Manual roll back to `pandas` version <= 1.0.5 might be required. We hope this MOB-Suite version will solve once an forever any dependency issues.
=> Updating MOB-Suite to version 3.0.1 

tools/staramr/staramr_search.xml
This updates the Galaxy tool version of starmar to `0.7.2` which is the latest in bioconda.
Version 0.7.2 fixed one small issue in staramr so that newer versions of pandas can be used (https://github.com/phac-nml/staramr/releases/tag/0.7.2).
=> Update staramr to 0.7.2

.travis.yml, tools/sistr_cmd/README.md, tools/sistr_cmd/sistr_cmd.xml
By testing SISTR in workflow context it was identified that sample names are not propagated throughout all workflow stages (assembly, serotyping, reporting) resulting in  inability to easily map samples back to their original inputs. I've made a very minor change by use of `element_identifier` field instead of `name` for genome names. This issue is discussed at [https://planemo.readthedocs.io/en/latest/writing_advanced.html?highlight=element_identifier#processing-identifiers](https://planemo.readthedocs.io/en/latest/writing_advanced.html?highlight=element_identifier#processing-identifiers)
=> Update SISTR to version 1.1.1+galaxy1

.github/workflows/pr.yaml
Fixes test suite so we don't run the same tests on both PRs and pushes to the same branch.
Double-testing (for PR and Push) can be observed for the staramr PR:
=> Tests only run on PRs

tools/staramr/staramr_search.xml
Merging https://github.com/phac-nml/galaxy_tools/pull/263 as part of updating the StarAMR wrapper.
=> Add bio.tools ref to staramr

tools/mob_suite/mob_recon.xml, tools/mob_suite/mob_typer.xml
This small patch fixes the optional `biomarker report` output in `MOB-Typer` and makes it a default option. This makes the GUI more friendly and useful for the users. That is why I decided to make small update to the recipe after using it myself. The biomarker report output will only be displayed if such option is selected (which it is now by default). In recipe `galaxy0` this report appears always regardless of the selection which is a bug
=> fixed optional rendering of the plasmid report in MOB-Typer with this new small patch
